# deployment-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dorm
  template:
    metadata:
      labels:
        app: dorm
    spec:
      initContainers:
        - name: sleep-init
          image: busybox
          command: [ 'sh', '-c', 'echo "Waiting for 2 minutes..."; sleep 120' ]
      containers:
        - name: dorm
          image: saadtaleb25314/dorm  # Image de Docker Hub
          ports:
            - containerPort: 8089  # Port que l'application écoute